FROM amazoncorretto:11
EXPOSE 8080
ARG JAR_FILE=/build/libs/offer-0.0.1-SNAPSHOT.jar
VOLUME ["/var/log"]
COPY ${JAR_FILE} offer-be-app.jar
COPY /home/github/offer-env/application-prod.yml /root/offer-env/application-prod.yml
ENTRYPOINT ["java","-jar","-Dspring.config.location=/root/offer-env/application-prod.yml","/offer-be-app.jar"]