FROM amazoncorretto:11
LABEL maintainer="Jihun Hwang <goharrm@gmail.com>"

EXPOSE 8080
VOLUME ["/var/log"]

ARG JAR_FILE=/build/libs/offer-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} offer-prod-app.jar

USER root
WORKDIR /

CMD yum update -y \
    && yum install -y procps \

ENTRYPOINT ["java","-jar","-Dspring.config.location=/spring-run-env/application-prod.yml","/offer-prod-app.jar"]
